### ISSUE TITLE
s3 blobstore authorization fails

### ISSUE THREAD

**Issue by robbertvanwaveren** [cf-platform-eng/aws-broker-boshrelease#1]
Seems that without any specific access config file, the aws-broker-boshrelease s3 bucket does not allow any downloads (anymore).

**Comment by frodenas** [comment]
I'm not sure I understand your problem. Theoretically, the [policy attached](https://github.com/cf-platform-eng/cloudformation-broker/blob/master/sample-s3-cftemplate.json#L24) to the bucket during the cloud formation creation process should allow the authenticated user to perform any s3 action agains the bucket.

Can you please clarify what error are you seeing?

**Comment by robbertvanwaveren** [comment]
What I meant was is that I'm unable to upload the boshreleases into my CF because the release points to an s3 bucket that does not allow me to download it.

**Comment by frodenas** [comment]
@Robbert1 Understood, thanks for the clarification. Yes, there was a missing bucket policy, now it should be fixed. 

Thanks for reporting this. Please reopen if you hit the same error.
