### ISSUE TITLE
502 Error trying to create aws services

### ISSUE THREAD

**Issue by m-richo** [cf-platform-eng/aws-broker-boshrelease#2]
Hi,
We run PCF in AWS and i wanted to use RDS as a our relational db service.  I deployed this AWS broker release using the .pivotal file/tile.  Installation and configuration seemed straight forward.  I can see the new services listed in the marketplace.  Unfortunately whenever i try to create any S3, RDS or SQS services i get a 502 error.

```
$ cf create-service aws-s3 bucket michaeltest
Creating service instance michaeltest in org dibp-permit-service / space test as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: RequestError: send request failed
```

Any thoughts on what might be the issue?

**Comment by frodenas** [comment]
I'd suggest enabling the broker "Debug" mode (if not already enabled), and then, using the `admin` user, check the `rds-broker` app logs (org `system` - space `aws-broker`). The broker should output a more detailed log. 

`502` is a generic error, might happen that the broker app cannot contact the AWS API endpoint. Have you checked the cf security groups? Is there a proxy involved?

**Comment by m-richo** [comment]
Thanks for the very fast response @frodenas!!.  

I've taken a look into the rds-broker logs.  It looks like it's a complete _User error_.  The logs showed it unable to resolve "rds.ap-southeast-2a.amazonaws.com".  I had entered the AWS region as "ap-southeast-2a".  It should be "ap-southeast-2".  I'm applying those updates now.  If that fixes things i'll close the issue.

As a side note, i noticed the README says it's _not_ production ready, but that it also hasn't had any updates for a few months.  Any thoughts on the future roadmap of this?  

Cheers,
Michael

**Comment by frodenas** [comment]
Glad to hear the logs provided a hint of what was wrong. Please let me known if the problem still persists after changing the AWS region.

This broker was part of an experiment to demonstrate the [updates to the Service Broker API](https://blog.pivotal.io/pivotal-cloud-foundry/products/a-look-at-cloud-foundrys-service-broker-updates), and has never been my intention to create a product. Said that, Pivotal is evaluating creating some service brokers for certain AWS services. Let me know if you're interested and I can put you in contact with the corresponding PM.

**Comment by m-richo** [comment]
Thanks Ferran.  It all works fine now!!  Our Spring app has connected and works well with a RDS db.

We have a few pre-sales contacts at Pivotal.  I'll raise AWS service brokers with them and try to get them to drive it.  If that doesn't go well i might come back to you in the future for some Pivotal PM contact details.

Cheers,
Michael
